name: Build wr30u-6.6 OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/jdjh520/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: wr30u-6.6.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part4.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialization environment
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y build-essential ccache cmake flex bison gawk gcc-multilib g++-multilib \
            libncurses5-dev python3 python3-pip unzip zip git curl wget rsync file tree \
            libelf-dev libssl-dev zlib1g-dev
          sudo timedatectl set-timezone "$TZ"

      - name: Clone source code
        run: git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Load feeds & diy-part1
        run: |
          [ -f $FEEDS_CONF ] && cp $FEEDS_CONF openwrt/feeds.conf.default
          chmod +x $DIY_P1_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH

      - name: Update & install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load config & diy-part4
        run: |
          [ -d files ] && cp -r files openwrt/
          [ -f $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH

      - name: Download dependencies
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)

      - name: Compile firmware
        id: compile
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FILE_DATE=_$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Organize firmware
        id: organize
        if: success()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware
        uses: actions/upload-artifact@v6
        with:
          name: OpenWrt_wr30u${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}
