name: Build wr30u-6.6 OpenWrt

on:
  workflow_dispatch:
  repository_dispatch:

env:
  REPO_URL: https://github.com/jdjh520/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6
  CONFIG_FILE: wr30u-6.6.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part4.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialization environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex libncurses-dev libssl-dev \
          git wget curl unzip bzip2 python3 python3-pip libelf-dev
          sudo timedatectl set-timezone "$TZ"

      - name: Clone source code
        run: git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Load feeds & diy1
        run: |
          chmod +x $DIY_P1_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load config & diy2
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH
          make defconfig

      - name: Download & compile
        run: |
          cd openwrt
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v6
        with:
          name: OpenWrt-wr30u-6.6
          path: openwrt/bin/targets/*/*
